import { Prisma } from "@/generated/prisma/client";

import { prisma } from "@/lib/prisma";
import type { AuditRequestMetadata } from "@/src/lib/audit-request-metadata";
import {
  buildCorrectionDeltaEmployeeSnapshot,
  buildEmployeePayRunSnapshot,
  toPayslipRecalcUpdateData,
  type PayRunEmployeeSnapshot,
} from "@/src/modules/payroll/lib/build-pay-run-snapshots";
import {
  moneyDiffCents,
  roundToCents,
  sumMoney,
} from "@/src/modules/payroll/lib/money";
import {
  aggregateIncludedPayRunTotals,
  filterIncludedPayRunRows,
  type PayRunMembershipStatus,
} from "@/src/modules/payroll/lib/pay-run-membership";
import { isPayRunMutable } from "@/src/modules/payroll/lib/pay-run-lifecycle";
import { isAutoGeneratedCorrectionLine } from "@/src/modules/payroll/lib/payroll-correction-delta";
import {
  loadPayrollOrganizationName,
  planCorrectionDeltaForEmployee,
  replaceAutoCorrectionLines,
} from "@/src/modules/payroll/services/sync-correction-delta-lines";

type DecimalLike = { toString(): string };

export type RecalculateDraftPayRunInput = {
  payRun: {
    id: string;
    organizationId?: string;
    runNumber: string;
    status: string;
    runKind?: "REGULAR" | "CORRECTION" | "OFF_CYCLE";
    sourcePayRunId?: string | null;
    payrollPeriod: {
      periodStart: Date;
      periodEnd: Date;
    };
    payslips: Array<{
      id: string;
      status: PayRunMembershipStatus;
      employeeId: string;
      employeeNumber: string;
      employeeName: string;
      grossPay: DecimalLike;
      totalDeductions: DecimalLike;
      netPay: DecimalLike;
      lineItems: Array<{
        lineType: "EARNING" | "DEDUCTION";
        code: string;
        label: string;
        amount: DecimalLike | number;
        isTaxable: boolean;
        notes?: string | null;
      }>;
    }>;
  };
  actorUserId: string;
  metadata: AuditRequestMetadata;
  /** When true, audit description notes forced pre-post refresh. */
  reason?: "manual" | "pre_post";
  /**
   * When false, leave approval fields untouched (used for pre-post refresh).
   * Caller must reject posting if figures changed.
   */
  clearApproval?: boolean;
};

export type RecalculateDraftPayRunResult =
  | {
      ok: true;
      employeeCount: number;
      excludedCount: number;
      totalGross: number;
      totalDeductions: number;
      totalNet: number;
      /** True when included net total changed vs pre-recalc values. */
      figuresChanged: boolean;
    }
  | { ok: false; message: string };

function decimalNumber(value: DecimalLike): number {
  return Number(value.toString());
}

/**
 * Rebuild included draft payslips from current master data + line items.
 * Used by manual Recalculate and automatically before Post (Wave A).
 *
 * CORRECTION runs with a sourcePayRun regenerate auto-delta CORRECTION_*
 * lines (idempotent replace) and rebuild delta-payment snapshots so the
 * run pays category differences — REGULAR / OFF_CYCLE keep full reassembly.
 */
export async function recalculateDraftPayRunCore(
  input: RecalculateDraftPayRunInput,
): Promise<RecalculateDraftPayRunResult> {
  if (!isPayRunMutable(input.payRun.status)) {
    return {
      ok: false,
      message: "Only draft or approved pay runs can be recalculated.",
    };
  }

  const included = filterIncludedPayRunRows(input.payRun.payslips);
  if (included.length === 0) {
    return {
      ok: false,
      message:
        "No included employees to recalculate. Re-include someone first, or create a new run.",
    };
  }

  const asOf = input.payRun.payrollPeriod.periodEnd;
  const isCorrectionDelta =
    input.payRun.runKind === "CORRECTION" &&
    Boolean(input.payRun.sourcePayRunId);

  const snapshots: Array<{ payslipId: string; row: PayRunEmployeeSnapshot }> =
    [];
  const notReadyAtCalc: string[] = [];

  let organizationId = input.payRun.organizationId;
  let organizationName = "";
  const sourceSnapshotByEmployee = new Map<string, unknown>();
  const plannedSuggestions = new Map<
    string,
    Awaited<ReturnType<typeof planCorrectionDeltaForEmployee>>["suggestedLines"]
  >();

  if (isCorrectionDelta) {
    const payRunRow =
      organizationId != null
        ? { organizationId, sourcePayRunId: input.payRun.sourcePayRunId! }
        : await prisma.payRun.findUnique({
            where: { id: input.payRun.id },
            select: { organizationId: true, sourcePayRunId: true },
          });

    if (!payRunRow?.sourcePayRunId) {
      return {
        ok: false,
        message: "Correction run is missing its source pay run link.",
      };
    }

    organizationId = payRunRow.organizationId;
    organizationName = await loadPayrollOrganizationName(organizationId);

    const sourceSlips = await prisma.payslip.findMany({
      where: {
        payRunId: payRunRow.sourcePayRunId,
        employeeId: { in: included.map((slip) => slip.employeeId) },
        status: "POSTED",
      },
      select: { employeeId: true, snapshot: true },
    });
    for (const slip of sourceSlips) {
      sourceSnapshotByEmployee.set(slip.employeeId, slip.snapshot);
    }

    for (const slip of included) {
      const planned = await planCorrectionDeltaForEmployee({
        employeeId: slip.employeeId,
        periodStart: input.payRun.payrollPeriod.periodStart,
        periodEnd: input.payRun.payrollPeriod.periodEnd,
        organizationName,
        sourceSnapshotRaw: sourceSnapshotByEmployee.get(slip.employeeId) ?? null,
        manualLines: slip.lineItems.filter(
          (line) => !isAutoGeneratedCorrectionLine(line.notes),
        ),
      });

      if (!planned.snapshot) {
        notReadyAtCalc.push(
          `${slip.employeeName} (${slip.employeeNumber}): ${
            planned.message || "Could not calculate correction delta."
          }`,
        );
        continue;
      }

      plannedSuggestions.set(slip.id, planned.suggestedLines);
      snapshots.push({ payslipId: slip.id, row: planned.snapshot });
    }
  } else {
    for (const slip of included) {
      const snapshot = await buildEmployeePayRunSnapshot(slip.employeeId, asOf, {
        periodStart: input.payRun.payrollPeriod.periodStart,
        periodEnd: input.payRun.payrollPeriod.periodEnd,
        lineItems: slip.lineItems,
      });

      if (!snapshot) {
        notReadyAtCalc.push(
          `${slip.employeeName} (${slip.employeeNumber}): employee record not found.`,
        );
        continue;
      }

      if (!snapshot.isReady) {
        notReadyAtCalc.push(
          `${snapshot.employeeName} (${snapshot.employeeNumber}): ${
            snapshot.blockingIssues.join(" ") || "Not payroll-ready."
          }`,
        );
        continue;
      }

      snapshots.push({ payslipId: slip.id, row: snapshot });
    }
  }

  if (notReadyAtCalc.length > 0) {
    return {
      ok: false,
      message: [
        "Cannot recalculate — some included employees are not payroll-ready:",
        ...notReadyAtCalc.map((line) => `• ${line}`),
      ].join("\n"),
    };
  }

  const excludedCount = input.payRun.payslips.length - included.length;
  const clearApproval = input.clearApproval !== false;

  const priorTotals = aggregateIncludedPayRunTotals(
    input.payRun.payslips.map((slip) => ({
      status: slip.status,
      grossPay: decimalNumber(slip.grossPay),
      totalDeductions: decimalNumber(slip.totalDeductions),
      netPay: decimalNumber(slip.netPay),
    })),
  );

  try {
    const totals = await prisma.$transaction(async (transaction) => {
      if (isCorrectionDelta && organizationId) {
        for (const entry of snapshots) {
          const slip = included.find((row) => row.id === entry.payslipId);
          if (!slip) {
            continue;
          }
          const suggested = plannedSuggestions.get(entry.payslipId) ?? [];
          await replaceAutoCorrectionLines({
            transaction,
            organizationId,
            payRunId: input.payRun.id,
            payslipId: slip.id,
            employeeId: slip.employeeId,
            actorUserId: input.actorUserId,
            suggestedLines: suggested,
            existingLines: slip.lineItems,
          });
        }
      }

      for (const entry of snapshots) {
        await transaction.payslip.update({
          where: { id: entry.payslipId },
          data: toPayslipRecalcUpdateData(entry.row),
        });
      }

      const amountRows = input.payRun.payslips.map((slip) => {
        const refreshed = snapshots.find(
          (entry) => entry.payslipId === slip.id,
        );
        if (refreshed) {
          return {
            status: slip.status,
            grossPay: refreshed.row.grossPay,
            totalDeductions: refreshed.row.totalDeductions,
            netPay: refreshed.row.netPay,
          };
        }
        return {
          status: slip.status,
          grossPay: decimalNumber(slip.grossPay),
          totalDeductions: decimalNumber(slip.totalDeductions),
          netPay: decimalNumber(slip.netPay),
        };
      });

      const aggregated = aggregateIncludedPayRunTotals(amountRows);
      const figuresChanged =
        moneyDiffCents(priorTotals.totalNet, aggregated.totalNet) !== 0 ||
        moneyDiffCents(priorTotals.totalGross, aggregated.totalGross) !== 0 ||
        moneyDiffCents(
          priorTotals.totalDeductions,
          aggregated.totalDeductions,
        ) !== 0;

      // Cent-exact control: header totals must equal sum of included slip nets.
      const summedNet = sumMoney(
        ...amountRows
          .filter((row) => row.status !== "EXCLUDED")
          .map((row) => row.netPay),
      );
      if (moneyDiffCents(aggregated.totalNet, summedNet) !== 0) {
        throw new Error(
          `Pay run net total mismatch after recalculation (${aggregated.totalNet} vs ${summedNet}).`,
        );
      }

      await transaction.payRun.update({
        where: { id: input.payRun.id },
        data: {
          employeeCount: aggregated.employeeCount,
          totalGross: new Prisma.Decimal(roundToCents(aggregated.totalGross)),
          totalDeductions: new Prisma.Decimal(
            roundToCents(aggregated.totalDeductions),
          ),
          totalNet: new Prisma.Decimal(roundToCents(aggregated.totalNet)),
          ...(clearApproval || figuresChanged
            ? {
                status: "DRAFT",
                approvedAt: null,
                approvedById: null,
                approvalNote: null,
              }
            : {}),
        },
      });

      const reasonLabel =
        input.reason === "pre_post"
          ? "Forced recalculation before post"
          : "Recalculated draft pay run";

      const autoLineCount = [...plannedSuggestions.values()].reduce(
        (sum, lines) => sum + lines.length,
        0,
      );

      await transaction.auditEvent.create({
        data: {
          userId: input.actorUserId,
          moduleKey: "payroll",
          action: "UPDATE",
          entityType: "PayRun",
          entityId: input.payRun.id,
          description: `${reasonLabel} ${input.payRun.runNumber} for ${aggregated.employeeCount} included employees${
            excludedCount > 0
              ? ` (${excludedCount} excluded preserved)`
              : ""
          }${
            isCorrectionDelta
              ? ` — refreshed ${autoLineCount} auto correction delta line${autoLineCount === 1 ? "" : "s"}`
              : ""
          }${figuresChanged ? " — figures changed" : " — figures unchanged"}.`,
          newValues: {
            employeeCount: aggregated.employeeCount,
            excludedCount,
            totalNet: aggregated.totalNet,
            totalGross: aggregated.totalGross,
            reason: input.reason ?? "manual",
            figuresChanged,
            approvalCleared: clearApproval || figuresChanged,
            ...(isCorrectionDelta
              ? { autoCorrectionLineCount: autoLineCount }
              : {}),
          },
          ipAddress: input.metadata.ipAddress,
          userAgent: input.metadata.userAgent,
          clientHostName: input.metadata.clientHostName,
        },
      });

      return { ...aggregated, figuresChanged };
    });

    return {
      ok: true,
      employeeCount: totals.employeeCount,
      excludedCount,
      totalGross: totals.totalGross,
      totalDeductions: totals.totalDeductions,
      totalNet: totals.totalNet,
      figuresChanged: totals.figuresChanged,
    };
  } catch (error) {
    return {
      ok: false,
      message:
        error instanceof Error
          ? error.message
          : "Could not recalculate the pay run.",
    };
  }
}

/**
 * Rebuild a single draft payslip after a line-item add/delete.
 * CORRECTION runs use delta-payment assembly from current lines (auto lines
 * are left as-is until a full Recalculate refreshes them).
 */
export async function rebuildDraftPayslipFromLineItems(input: {
  payRun: {
    id: string;
    organizationId: string;
    status: string;
    runKind: "REGULAR" | "CORRECTION" | "OFF_CYCLE";
    payrollPeriod: { periodStart: Date; periodEnd: Date };
  };
  payslip: {
    id: string;
    status: string;
    employeeId: string;
    employeeNumber?: string;
    employeeName?: string;
    lineItems: Array<{
      lineType: "EARNING" | "DEDUCTION";
      code: string;
      label: string;
      amount: DecimalLike | number;
      isTaxable: boolean;
      notes?: string | null;
    }>;
  };
  siblingPayslips: Array<{
    id: string;
    status: PayRunMembershipStatus;
    grossPay: DecimalLike;
    totalDeductions: DecimalLike;
    netPay: DecimalLike;
  }>;
}): Promise<{ ok: true; snapshot: PayRunEmployeeSnapshot } | { ok: false; message: string }> {
  if (!isPayRunMutable(input.payRun.status)) {
    return {
      ok: false,
      message: "Only draft or approved pay runs can be updated.",
    };
  }

  if (input.payslip.status !== "DRAFT") {
    return { ok: false, message: "Only included draft payslips can be updated." };
  }

  let snapshot: PayRunEmployeeSnapshot | null = null;

  if (input.payRun.runKind === "CORRECTION") {
    const organizationName = await loadPayrollOrganizationName(
      input.payRun.organizationId,
    );
    const identity = await buildEmployeePayRunSnapshot(
      input.payslip.employeeId,
      input.payRun.payrollPeriod.periodEnd,
      {
        periodStart: input.payRun.payrollPeriod.periodStart,
        periodEnd: input.payRun.payrollPeriod.periodEnd,
      },
    );

    if (!identity || !identity.isReady) {
      return {
        ok: false,
        message:
          identity?.blockingIssues.join(" ") ||
          "Could not calculate payslip snapshot.",
      };
    }

    snapshot = buildCorrectionDeltaEmployeeSnapshot({
      employeeId: input.payslip.employeeId,
      currency: identity.currency,
      employeeNumber: identity.employeeNumber,
      employeeName: identity.employeeName,
      nisNumber: identity.nisNumber,
      birNumber: identity.birNumber,
      jobTitle: identity.jobTitle,
      departmentName: identity.departmentName,
      payFrequency: identity.payFrequency,
      paymentMethod: identity.paymentMethod,
      organizationName,
      periodLabel: identity.snapshot.payslip.period.label,
      periodAsOf: identity.snapshot.payslip.period.asOf,
      lineItems: input.payslip.lineItems.map((line) => ({
        lineType: line.lineType,
        code: line.code,
        label: line.label,
        amount: Number(line.amount.toString()),
        isTaxable: line.isTaxable,
        notes: line.notes ?? null,
      })),
      isReady: true,
      blockingIssues: [],
    });
  } else {
    snapshot = await buildEmployeePayRunSnapshot(
      input.payslip.employeeId,
      input.payRun.payrollPeriod.periodEnd,
      {
        periodStart: input.payRun.payrollPeriod.periodStart,
        periodEnd: input.payRun.payrollPeriod.periodEnd,
        lineItems: input.payslip.lineItems,
      },
    );

    if (!snapshot || !snapshot.isReady) {
      return {
        ok: false,
        message:
          snapshot?.blockingIssues.join(" ") ||
          "Could not calculate payslip snapshot.",
      };
    }
  }

  await prisma.$transaction(async (transaction) => {
    await transaction.payslip.update({
      where: { id: input.payslip.id },
      data: toPayslipRecalcUpdateData(snapshot!),
    });

    const amountRows = input.siblingPayslips.map((row) =>
      row.id === input.payslip.id
        ? {
            status: row.status,
            grossPay: snapshot!.grossPay,
            totalDeductions: snapshot!.totalDeductions,
            netPay: snapshot!.netPay,
          }
        : {
            status: row.status,
            grossPay: decimalNumber(row.grossPay),
            totalDeductions: decimalNumber(row.totalDeductions),
            netPay: decimalNumber(row.netPay),
          },
    );
    const totals = aggregateIncludedPayRunTotals(amountRows);

    await transaction.payRun.update({
      where: { id: input.payRun.id },
      data: {
        employeeCount: totals.employeeCount,
        totalGross: new Prisma.Decimal(totals.totalGross),
        totalDeductions: new Prisma.Decimal(totals.totalDeductions),
        totalNet: new Prisma.Decimal(totals.totalNet),
        status: "DRAFT",
        approvedAt: null,
        approvedById: null,
        approvalNote: null,
      },
    });
  });

  return { ok: true, snapshot };
}
