import { Prisma } from "@/generated/prisma/client";

import { prisma } from "@/lib/prisma";
import {
  buildCorrectionDeltaEmployeeSnapshot,
  buildEmployeePayRunSnapshot,
  type CorrectionDeltaLineInput,
  type PayRunEmployeeSnapshot,
} from "@/src/modules/payroll/lib/build-pay-run-snapshots";
import {
  computeSuggestedCorrectionLines,
  isAutoGeneratedCorrectionLine,
  AUTO_DELTA_NOTES_PREFIX,
  type SuggestedCorrectionLine,
} from "@/src/modules/payroll/lib/payroll-correction-delta";
import { parsePayslipSnapshot } from "@/src/modules/payroll/lib/payslip-snapshot";

type DecimalLike = { toString(): string };

export type ManualCorrectionLine = {
  id?: string;
  lineType: "EARNING" | "DEDUCTION";
  code: string;
  label: string;
  amount: DecimalLike | number;
  isTaxable: boolean;
  notes?: string | null;
};

/**
 * Phase B: for a CORRECTION employee, compare source posted snapshot to a
 * current reassembled preview and produce auto CORRECTION_* lines + a
 * delta-payment payslip snapshot (manual lines preserved).
 */
export async function planCorrectionDeltaForEmployee(input: {
  employeeId: string;
  periodStart: Date;
  periodEnd: Date;
  organizationName: string;
  /** Posted source payslip snapshot JSON (may be null if employee was not on source). */
  sourceSnapshotRaw: unknown | null;
  /** Officer-entered lines to keep (auto-tagged lines are ignored here). */
  manualLines: ManualCorrectionLine[];
}): Promise<{
  suggestedLines: SuggestedCorrectionLine[];
  allLines: CorrectionDeltaLineInput[];
  snapshot: PayRunEmployeeSnapshot | null;
  message?: string;
}> {
  const target = await buildEmployeePayRunSnapshot(
    input.employeeId,
    input.periodEnd,
    {
      periodStart: input.periodStart,
      periodEnd: input.periodEnd,
    },
  );

  if (!target) {
    return {
      suggestedLines: [],
      allLines: [],
      snapshot: null,
      message: "Employee record not found.",
    };
  }

  if (!target.isReady) {
    return {
      suggestedLines: [],
      allLines: [],
      snapshot: null,
      message:
        target.blockingIssues.join(" ") || "Employee is not payroll-ready.",
    };
  }

  const sourceParsed = input.sourceSnapshotRaw
    ? parsePayslipSnapshot(input.sourceSnapshotRaw)
    : null;

  const suggestedLines = computeSuggestedCorrectionLines({
    sourcePayslip: sourceParsed?.payslip ?? null,
    targetPayslip: target.snapshot.payslip,
  });

  const manualAsLines: CorrectionDeltaLineInput[] = input.manualLines
    .filter((line) => !isAutoGeneratedCorrectionLine(line.notes))
    .map((line) => ({
      lineType: line.lineType,
      code: line.code,
      label: line.label,
      amount: Number(line.amount.toString()),
      isTaxable: line.isTaxable,
      notes: line.notes ?? null,
    }));

  const allLines: CorrectionDeltaLineInput[] = [
    ...suggestedLines.map((line) => ({
      lineType: line.lineType,
      code: line.code,
      label: line.label,
      amount: line.amount,
      isTaxable: line.isTaxable,
      notes: line.notes,
    })),
    ...manualAsLines,
  ];

  const snapshot = buildCorrectionDeltaEmployeeSnapshot({
    employeeId: input.employeeId,
    currency: target.currency,
    employeeNumber: target.employeeNumber,
    employeeName: target.employeeName,
    nisNumber: target.nisNumber,
    birNumber: target.birNumber,
    jobTitle: target.jobTitle,
    departmentName: target.departmentName,
    payFrequency: target.payFrequency,
    paymentMethod: target.paymentMethod,
    organizationName: input.organizationName,
    periodLabel: target.snapshot.payslip.period.label,
    periodAsOf: target.snapshot.payslip.period.asOf,
    lineItems: allLines,
    isReady: true,
    blockingIssues: [],
  });

  return { suggestedLines, allLines, snapshot };
}

/**
 * Replace auto-delta PayrollLineItem rows for one payslip and return the
 * lines that should drive the delta payslip (suggested + remaining manual).
 */
export async function replaceAutoCorrectionLines(input: {
  transaction: Prisma.TransactionClient;
  organizationId: string;
  payRunId: string;
  payslipId: string;
  employeeId: string;
  actorUserId: string | null;
  suggestedLines: SuggestedCorrectionLine[];
  /** Existing lines on the slip (before delete). */
  existingLines: ManualCorrectionLine[];
}): Promise<CorrectionDeltaLineInput[]> {
  const manualLines = input.existingLines.filter(
    (line) => !isAutoGeneratedCorrectionLine(line.notes),
  );

  await input.transaction.payrollLineItem.deleteMany({
    where: {
      payslipId: input.payslipId,
      notes: { startsWith: AUTO_DELTA_NOTES_PREFIX },
    },
  });

  if (input.suggestedLines.length > 0) {
    await input.transaction.payrollLineItem.createMany({
      data: input.suggestedLines.map((line) => ({
        organizationId: input.organizationId,
        payRunId: input.payRunId,
        payslipId: input.payslipId,
        employeeId: input.employeeId,
        lineType: line.lineType,
        code: line.code,
        label: line.label,
        amount: new Prisma.Decimal(line.amount),
        isTaxable: line.isTaxable,
        notes: line.notes,
        createdById: input.actorUserId,
      })),
    });
  }

  return [
    ...input.suggestedLines.map((line) => ({
      lineType: line.lineType,
      code: line.code,
      label: line.label,
      amount: line.amount,
      isTaxable: line.isTaxable,
      notes: line.notes,
    })),
    ...manualLines.map((line) => ({
      lineType: line.lineType,
      code: line.code,
      label: line.label,
      amount: Number(line.amount.toString()),
      isTaxable: line.isTaxable,
      notes: line.notes ?? null,
    })),
  ];
}

/** Load organization display name for delta snapshot meta. */
export async function loadPayrollOrganizationName(
  organizationId: string,
): Promise<string> {
  const org = await prisma.organization.findUnique({
    where: { id: organizationId },
    select: { name: true, shortName: true },
  });
  return org?.shortName || org?.name || "Organization";
}
