import { describe, expect, it } from "vitest";

import {
  computeCategoryDeltas,
  computePayslipDelta,
  computeSuggestedCorrectionLines,
  extractPayslipCategoryAmounts,
  formatSignedMoney,
  isAutoGeneratedCorrectionLine,
  netDeltaDirection,
  suggestedCorrectionLinesFromCategoryDelta,
  type PayslipCategoryAmounts,
} from "@/src/modules/payroll/lib/payroll-correction-delta";
import type { PayslipPreview } from "@/src/modules/payroll/lib/payslip-preview";

function makePayslip(
  partial: Partial<PayslipPreview> & {
    grossPay: number;
    totalDeductions: number;
    netPay: number;
    deductions?: PayslipPreview["deductions"];
  },
): PayslipPreview {
  const {
    grossPay,
    totalDeductions,
    netPay,
    deductions = [],
    ...rest
  } = partial;

  return {
    employee: {
      id: "emp-1",
      employeeNumber: "E001",
      displayName: "Test Employee",
      nisNumber: null,
      birNumber: null,
    },
    period: {
      label: "January 2026",
      asOf: "2026-01-31",
      payFrequency: "MONTHLY",
      paymentMethod: "BANK_TRANSFER",
    },
    currency: "TTD",
    earnings: [{ label: "Base salary", amount: grossPay }],
    baseSalary: grossPay,
    allowancesTotal: 0,
    grossPay,
    monthlyTaxableEarnings: grossPay,
    deductions,
    totalDeductions,
    netPay,
    employerContributions: [],
    bankDistribution: null,
    nis: null,
    paye: null,
    health: null,
    readiness: { isReady: true, blockingIssues: [] },
    warnings: [],
    notes: [],
    ...rest,
  };
}

describe("computePayslipDelta", () => {
  it("returns correction minus original for each total", () => {
    const delta = computePayslipDelta(
      { grossPay: 12000, totalDeductions: 3200, netPay: 8800 },
      { grossPay: 10000, totalDeductions: 3000, netPay: 7000 },
    );

    expect(delta).toEqual({
      grossPay: 2000,
      totalDeductions: 200,
      netPay: 1800,
    });
  });

  it("handles negative corrections (clawback)", () => {
    const delta = computePayslipDelta(
      { grossPay: 9000, totalDeductions: 2800, netPay: 6200 },
      { grossPay: 10000, totalDeductions: 3000, netPay: 7000 },
    );

    expect(delta?.grossPay).toBe(-1000);
    expect(delta?.netPay).toBe(-800);
  });

  it("rounds to cents to avoid float drift", () => {
    const delta = computePayslipDelta(
      { grossPay: 100.1, totalDeductions: 0, netPay: 100.1 },
      { grossPay: 100.0, totalDeductions: 0, netPay: 100.0 },
    );

    expect(delta?.grossPay).toBeCloseTo(0.1, 5);
    expect(delta?.netPay).toBe(0.1);
  });

  it("returns null when there is no original to compare", () => {
    expect(
      computePayslipDelta(
        { grossPay: 5000, totalDeductions: 1000, netPay: 4000 },
        null,
      ),
    ).toBeNull();
  });
});

describe("netDeltaDirection", () => {
  it("classifies increases, decreases, and no change", () => {
    expect(
      netDeltaDirection({ grossPay: 0, totalDeductions: 0, netPay: 10 }),
    ).toBe("increase");
    expect(
      netDeltaDirection({ grossPay: 0, totalDeductions: 0, netPay: -10 }),
    ).toBe("decrease");
    expect(
      netDeltaDirection({ grossPay: 0, totalDeductions: 0, netPay: 0 }),
    ).toBe("none");
    expect(netDeltaDirection(null)).toBe("none");
  });
});

describe("formatSignedMoney", () => {
  it("prefixes a sign and never renders negative zero", () => {
    expect(formatSignedMoney(1234.5, { currency: "TTD" })).toBe("+TTD 1,234.50");
    expect(formatSignedMoney(-1234.5)).toBe("-1,234.50");
    expect(formatSignedMoney(0, { currency: "TTD" })).toBe("TTD 0.00");
    expect(formatSignedMoney(-0)).toBe("0.00");
  });
});

describe("line-level category deltas", () => {
  const sourceAmounts: PayslipCategoryAmounts = {
    grossEarnings: 10000,
    paye: 1500,
    nisEmployee: 400,
    healthSurcharge: 100,
    otherDeductions: 0,
  };

  it("returns no suggested lines when nothing changed", () => {
    const lines = suggestedCorrectionLinesFromCategoryDelta(
      computeCategoryDeltas(sourceAmounts, sourceAmounts),
    );
    expect(lines).toEqual([]);
  });

  it("suggests CORRECTION_EARNING when gross earnings increase", () => {
    const target: PayslipCategoryAmounts = {
      ...sourceAmounts,
      grossEarnings: 11500,
      paye: 1650,
    };
    const lines = suggestedCorrectionLinesFromCategoryDelta(
      computeCategoryDeltas(target, sourceAmounts),
    );

    expect(lines).toEqual([
      expect.objectContaining({
        categoryKey: "grossEarnings",
        code: "CORRECTION_EARNING",
        amount: 1500,
        lineType: "EARNING",
      }),
      expect.objectContaining({
        categoryKey: "paye",
        code: "CORRECTION_DEDUCTION",
        amount: 150,
        lineType: "DEDUCTION",
        label: "PAYE (income tax)",
      }),
    ]);
    expect(lines.every((line) => isAutoGeneratedCorrectionLine(line.notes))).toBe(
      true,
    );
  });

  it("suggests signed CORRECTION_DEDUCTION when a deduction decreases (refund)", () => {
    const target: PayslipCategoryAmounts = {
      ...sourceAmounts,
      nisEmployee: 300,
    };
    const lines = suggestedCorrectionLinesFromCategoryDelta(
      computeCategoryDeltas(target, sourceAmounts),
    );

    expect(lines).toEqual([
      expect.objectContaining({
        categoryKey: "nisEmployee",
        code: "CORRECTION_DEDUCTION",
        amount: -100,
        label: "NIS (employee)",
      }),
    ]);
  });

  it("extracts categories from a payslip preview", () => {
    const payslip = makePayslip({
      grossPay: 10000,
      totalDeductions: 2000,
      netPay: 8000,
      deductions: [
        { label: "PAYE (income tax)", amount: 1400 },
        { label: "NIS (employee)", amount: 400 },
        { label: "Health Surcharge", amount: 100 },
        { label: "Loan", amount: 100 },
      ],
    });

    expect(extractPayslipCategoryAmounts(payslip)).toEqual({
      grossEarnings: 10000,
      paye: 1400,
      nisEmployee: 400,
      healthSurcharge: 100,
      otherDeductions: 100,
    });
  });

  it("returns no lines when source or target is missing (e.g. excluded / no source)", () => {
    const target = makePayslip({
      grossPay: 11000,
      totalDeductions: 2000,
      netPay: 9000,
      deductions: [{ label: "PAYE (income tax)", amount: 2000 }],
    });

    expect(
      computeSuggestedCorrectionLines({
        sourcePayslip: null,
        targetPayslip: target,
      }),
    ).toEqual([]);

    expect(
      computeSuggestedCorrectionLines({
        sourcePayslip: target,
        targetPayslip: null,
      }),
    ).toEqual([]);
  });

  it("computes suggested lines from source vs target payslips end-to-end", () => {
    const source = makePayslip({
      grossPay: 10000,
      totalDeductions: 2000,
      netPay: 8000,
      deductions: [
        { label: "PAYE (income tax)", amount: 1500 },
        { label: "NIS (employee)", amount: 400 },
        { label: "Health Surcharge", amount: 100 },
      ],
    });
    const target = makePayslip({
      grossPay: 12000,
      totalDeductions: 2300,
      netPay: 9700,
      deductions: [
        { label: "PAYE (income tax)", amount: 1700 },
        { label: "NIS (employee)", amount: 450 },
        { label: "Health Surcharge", amount: 150 },
      ],
    });

    const lines = computeSuggestedCorrectionLines({
      sourcePayslip: source,
      targetPayslip: target,
    });

    expect(lines.map((line) => [line.categoryKey, line.amount])).toEqual([
      ["grossEarnings", 2000],
      ["paye", 200],
      ["nisEmployee", 50],
      ["healthSurcharge", 50],
    ]);
  });
});
